### ISSUE TITLE
FullTclash 运行python3 main.py提示错误该怎么解决？

### ISSUE THREAD

**Issue by wzry2580** [AirportR/FullTclash#124]
Traceback (most recent call last):
  File "/root/FullTclash/main.py", line 1, in <module>
    from utils import bot
  File "/root/FullTclash/utils/bot.py", line 6, in <module>
    import botmodule
  File "/root/FullTclash/botmodule/init.py", line 1, in <module>
    from botmodule.command.grant import *
  File "/root/FullTclash/botmodule/command/grant.py", line 9, in <module>
    from botmodule.init_bot import admin, config, reloadUser, proxy_subprocess
  File "/root/FullTclash/botmodule/init_bot.py", line 135, in <module>
    api_id = botconfig.get('api_id', None)
AttributeError: 'str' object has no attribute 'get'

我不知道怎么办，所以问一下

**Comment by AirportR** [comment]
配置写错了，检查一下
